<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('waitlist_signups', function (Blueprint $table) {
            // Primary key (using _id to match BaseModel pattern)
            $table->bigIncrements('_id');

            // Unique identifier (auto-generated by BaseModel)
            $table->string('_uid', 36)->unique();

            // User information
            $table->string('full_name', 100);
            $table->string('email', 255)->unique();
            $table->text('interest'); // JSON array

            // Status: 1=pending, 2=invited, 3=activated, 4=expired
            $table->tinyInteger('status')->default(1);

            // FIFO priority ordering
            $table->integer('priority_score')->default(0);

            // Invitation tracking
            $table->timestamp('invitation_sent_at')->nullable();
            $table->string('invitation_token', 255)->nullable()->unique();
            $table->timestamp('invitation_expires_at')->nullable();

            // Activation tracking
            $table->timestamp('activated_at')->nullable();
            $table->bigInteger('user_id')->nullable(); // FK to users._id

            // Admin notes
            $table->text('notes')->nullable();

            // Timestamps
            $table->timestamps();

            // Indexes for performance
            $table->index('email');
            $table->index('invitation_token');
            $table->index('status');
            $table->index('priority_score');
            $table->index(['status', 'priority_score']); // Composite index for FIFO queries
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('waitlist_signups', function (Blueprint $table) {
            // Drop composite index first
            $table->dropIndex(['status', 'priority_score']);

            // Drop single column indexes
            $table->dropIndex(['email']);
            $table->dropIndex(['invitation_token']);
            $table->dropIndex(['status']);
            $table->dropIndex(['priority_score']);
        });

        Schema::dropIfExists('waitlist_signups');
    }
};
